name: Testings
on: workflow_dispatch
# on:
#   release:
#     types: [published]
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
  
      - name: Initialize Git user
        run: |
          git switch dev
          git rebase origin/main
          