name: deploy
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Git
        run: |
          tag=$(git describe --tags --abbrev=0)
          echo $tag