name: Release
on:
  push:
    branches:
      - main
      - dev
      - feature/**
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install the dependancies
      run: npm ci

    - name: Initialize Git user
      run: |
        git config user.name "GitHub Action Bot"
        git config user.email "<>"

    - name: Run release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ ${{github.ref_name}} == 'main' ]; then
          npx release-it --ci
        elif [ ${{github.ref_name}} == 'dev' ]; then
          npx release-it --preRelease=rc --ci
        else
          npx release-it --preRelease=beta --ci
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/hkaibara/test-app-wf-release-it/actions/workflows/backMerge.yml/dispatches \
            -d '{"ref":"main"}'
        fi
        version=$(jq -r '.version' package.json)
        echo $version