name: Release
# on: workflow_dispatch
on:
  push:
    branches:
      - main
      - dev
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Install the dependancies
      run: npm ci

    - name: Initialize Git user
      run: |
        git config user.name "GitHub Action Bot"
        git config user.email "<>"

    - name: Log git status
      run: git status
    - name: What is the event?
      run: |
        if [ ${{ github.event_name }} == 'pull_request' ]; then
          echo "This is a pull request event"
        elif [ ${{ github.event_name }} == 'push' ]; then
          echo "This is a push event"
        else
          echo "This is an unknown event"
        fi
    - name: Run release
      run: |
        if ["${{github.ref_name}}" == "dev"]; then
          npx release-it --preRelease=alpha --ci
        else
          npx release-it --ci
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}